App\Document\Feed:
    attributes:
        id: 
            groups: ['feed']
        title_es: 
            groups: ['feed']
        description_es: 
            groups: ['feed']
        city: 
            groups: ['feed']
        price_amount: 
            groups: ['feed']
        country: 
            groups: ['feed']
        video: 
            groups: ['feed']
        image_0: 
            groups: ['feed']
        image_1: 
            groups: ['feed']
        image_2: 
            groups: ['feed']
        image_3: 
            groups: ['feed']
        image_4: 
            groups: ['feed']